### ISSUE TITLE
Getting compilation error

### ISSUE THREAD

**Issue by harish31** [jipipayo/pdi-redis-plugin#2]
![stackoutput](https://cloud.githubusercontent.com/assets/10463219/5679622/290f814a-9828-11e4-9fbc-59c0f234d48b.png)

**Comment by jipipayo** [comment]
hi @harish31 ! thanks for your interest on this plugin, but the plugin is on an very early stage, almost a stub.  I am sorry you wasted your time with a plugin that is not functional.

**Comment by harish31** [comment]
Can you please suggest me any method using which i can connect to redis
using kettle.
Regards
harish

**Comment by jipipayo** [comment]
not from kettle as far as i know, but maybe you could build a simple web rest wrapper api in php, perl, ruby, whatever language you like  and then user the REST step from kettle.
hope it helps . cheers!
